---
- name: Configure name servers
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: "{{ item }}"
  loop:
    - DNS1={{ '.'.join(ansible_facts.default_ipv4.address.split('.')[0:3]) }}.13
    - DNS2=1.1.1.1
    - DNS3=1.1.1.1

- name: Restart network
  service:
    name: network
    state: restarted
