---
- name: Config NFS
  lineinfile:
    path: /etc/exports
    line: /var/log/squid {{ '.'.join(ansible_facts.default_ipv4.address.split('.')[0:3]) }}.23/25(ro,sync,no_all_squash,no_root_squash)

- name: exportfs
  shell: exportfs -arv
