---
- name: Configure kernel
  lineinfile:
    path: /etc/sysctl.conf
    line: "{{ item }}"
  loop:
    - net.ipv4.ip_forward = 1
    - net.ipv4.conf.default.rp_filter = 0
    - net.ipv4.conf.all.rp_filter = 0
    - net.ipv4.conf.default.rp_filter = 0
    - net.ipv4.conf.eth0.rp_filter = 0
    - net.ipv4.conf.gre0.rp_filter = 0
    - net.ipv4.conf.gretap0.rp_filter = 0
    - net.ipv4.conf.lo.rp_filter = 0
    - net.ipv4.conf.wccp0.rp_filter = 0
